language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip
            - curl
            - rsync

install:
    - "export PATH=$PWD/bin:$PATH"
#    - "cpanm --quiet --notest File::Which"

script:
    - "seeka --version"
    - "seeka --help"
